version: "3"

volumes:
    prometheus_data: {}
    grafana: {}

services:
  prom:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
      - ./prometheus/:/etc/prometheus/ #prometheus以下をmapping
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
     - 9090:9090
    depends_on:
     - exporter
  exporter:
    image: prom/node-exporter:latest
    ports:
     - "9100:9100"
#    network_mode: host
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    depends_on:
      - prom